### ISSUE TITLE
Can't connect to the BOINC server

### ISSUE THREAD

**Issue by its5Q** [nesfit/fitcrack#15]
I've forked this repository and updated the BOINC server to be able to run fitcrack with MySQL 8+. However, after overcoming a lot of errors, I've come to a dead end. The frontend and backend are working fine, but I can't connect to the BOINC server. When using BOINC Manager, I get an error while registering an account. Trying it with boinccmd, the registration goes fine, and the project shows up in the manager, but it says "No jobs to process", and I can't see it in the host list from the dashboard. I've looked at apache's access.log, but other than the register GET request, no other requests are being made. Can I get some help?

EDIT: I'm using Ubuntu 20.04 LTS, and actually, some of the backend stuff is broken too, like resource usage monitoring. My current setup is at http://178.250.159.53/

**Comment by ihranicky** [comment]
Hello, on your server, I see the following:
- The WebAdmin and the database seem to be running okay.
- Some essential daemons (work_generator, assimilator, validator) are **not** loaded.
- http://178.250.159.53/fitcrack/ contains links to 127.0.0.1 (localhost) instead of your IP.

I believe, the problem is the configuration of the **URL_BASE** at install time. Therefore, I recommend:
- Using the installer (option 4) remove the **fitcrack** project (or remove everything),
- Perform a clean install and when prompted to  **Enter BOINC project URL_BASE (default: http://127.0.0.1):** type **http://178.250.159.53**

Basically, for each file (binaries, cracking-related data, etc.) that should be transmitted to hosts, BOINC server gives hosts a download link. Hosts the access the resources on the server using these URLs. Every link starts with the **URL_BASE**. With the setting of **http://127.0.0.1**, only locally-installed BOINC client can work - i.e., client and server is on a single machine, which is usually enough for testing and development. If you wish to make the server accessible over the network, you need to change the **URL_BASE** to match your IP or domain.

Good luck and please, let me know if that helped :)

Best Regards
Radek

**Comment by its5Q** [comment]
Thanks for the help! I did a "dirty" install over my existing fitcrack installation, saying "yes" when asked to reinstall, now the BOINC server works great, I can register, and I can see my host in the webadmin. Now, you said there are essential daemons which are not running. How can I try to diagnose why they aren't running? By the way, if work_generator, assimilator and validator should be in the bin folder, I have only assimilator.py, but the other 2 are missing.

**Comment by its5Q** [comment]
Thanks for the detailed reply. I have 3 daemons in config.xml:
- feeder
- transitioner
- file_deleter
The ./bin/status shows them all running.
The WebAdmin shows that everything is running.
And the server_status.php tells me the same.

Looking at the boinc/sched directory, I can the the cpp files for those binaries, but no binaries built. Running make in the **BOINC** directory doesn't throw any errors, but doesn't build those binaries either. So it must be something with the compilation, not with the project installation.

**Comment by its5Q** [comment]
Update: I've found that ./configure throws an error, I will look into it and update with my progress.

**Comment by ihranicky** [comment]
(Yes, the sample_ daemons are not needed.)
All right, there must be a compilation issue. I recommend:

Making a fresh clone of master:
https://github.com/nesfit/fitcrack

Trying manually what the `installer/build_server.sh` script does.

**First, copy our sources and headers** to **boinc/sched** directory:
`cp -f server/src/headers/*.h              boinc/sched/
cp -f server/src/headers/AttackModes/*.h  boinc/sched/
cp -f server/src/headers/Generators/*.h   boinc/sched/
cp -f server/src/headers/Database/*.h     boinc/sched/
cp -f server/src/headers/Utils/*.h        boinc/sched/
cp -f server/src/source/*.cpp             boinc/sched/
cp -f server/src/source/AttackModes/*.cpp boinc/sched/
cp -f server/src/source/Generators/*.cpp  boinc/sched/
cp -f server/src/source/Database/*.cpp    boinc/sched/
cp -f server/src/source/Utils/*.cpp       boinc/sched/
cp -f server/src/headers/protocol/*.cc    boinc/sched/
cp -f server/src/headers/protocol/*.h     boinc/sched/
cp -rf server/src/include/*               boinc/sched/`

Then:
`cd boinc
chmod +x _autosetup
./configure --disable-client --disable-manager
make`

And check the **boinc/sched/bin** for the binaries.

**Comment by ihranicky** [comment]
> 
> 
> Update: I've found that ./configure throws an error, I will look into it and update with my progress.
> Edit: no errors when configuring with no client and manager

This is very strange. Well, we can debug deeper. In **boibc/sched**, there is another Makefile. Try `make clean && make` here.

Or you can try just to build individual modules, for instance:
`make work_generator`
or
`make assimilator`

**Comment by its5Q** [comment]
> > Update: I've found that ./configure throws an error, I will look into it and update with my progress.
> > Edit: no errors when configuring with no client and manager
> 
> This is very strange. Well, we can debug deeper. In **boinc/sched**, there is another Makefile. Try `make clean && make` here.
> 
> Or you can try just to build individual modules, for instance:
> `make work_generator`
> or
> `make assimilator`

I can confirm that I messed up with the boinc update, because I thought that the make file was patched like other stuff, but it turns out the makefile was edited to include those cpp files, I've now got the exact makefile from your repository, and I hope this time everything will be working. Thanks for the help.

**Comment by ihranicky** [comment]
> 
> 
> > > Update: I've found that ./configure throws an error, I will look into it and update with my progress.
> > > Edit: no errors when configuring with no client and manager
> > 
> > 
> > This is very strange. Well, we can debug deeper. In **boinc/sched**, there is another Makefile. Try `make clean && make` here.
> > Or you can try just to build individual modules, for instance:
> > `make work_generator`
> > or
> > `make assimilator`
> 
> I can confirm that I messed up with the boinc update, because I thought that the make file was patched like other stuff, but it turns out the makefile was edited to include those cpp files, I've now got the exact makefile from your repository, and I hope this time everything will be working. Thanks for the help.

I see, you are fixing it in you fork now. Good luck.

Originally, we used the patching only. But boinc later required more changes, so we modified it directly. There are changes from the original BOINC repo, not just in makefiles, but also in other places like
https://github.com/nesfit/fitcrack/blob/master/boinc/tools/make_project

**Comment by its5Q** [comment]
> > > > Update: I've found that ./configure throws an error, I will look into it and update with my progress.
> > > > Edit: no errors when configuring with no client and manager
> > > 
> > > 
> > > This is very strange. Well, we can debug deeper. In **boinc/sched**, there is another Makefile. Try `make clean && make` here.
> > > Or you can try just to build individual modules, for instance:
> > > `make work_generator`
> > > or
> > > `make assimilator`
> > 
> > 
> > I can confirm that I messed up with the boinc update, because I thought that the make file was patched like other stuff, but it turns out the makefile was edited to include those cpp files, I've now got the exact makefile from your repository, and I hope this time everything will be working. Thanks for the help.
> 
> I see, you are fixing it in you fork now. Good luck.
> 
> Originally, we used the patching only. But boinc later required more changes, so we modified it directly. There are changes from the original BOINC repo, not just in makefiles, but also in other places like
> https://github.com/nesfit/fitcrack/blob/master/boinc/tools/make_project

Yes, I already found that make_project file and copied it over too. I've forked the project so I could do support for Ubuntu 20.04, because that's what I'm using, and it was mostly issues with MySQL 8, but I decided that it would just be better upgrading the whole BOINC library/server. If you want, after it's all tested we can do a separate branch for the 20.04 version.

**Comment by davidbolvansky** [comment]
dev branch now works with 20.04.
