### ISSUE TITLE
ImportError: cannot import name 'ContextVar'

### ISSUE THREAD

**Issue by topsirloin** [nesfit/fitcrack#17]
I have attempted the installation of fitcrack on two different ubuntu 18.04 machines.  In both instances, when I try to access http://localhost It appears to start to launch, but fails with a red network error box.

I CAN access localhost/fitcrack to access the user log in, just not the main dashboard.

I reviewed the apache2 error.log, and there are many Traceback errors in relation to flask and  'ImportError: cannot import name 'ContextVar' errors.  

Is this error common in the apache2 logs? I'm wondering if there is a relation to the dashboard not launching and these errors?

**Comment by cmprmsd** [comment]
I managed to get the installation working (at least no errors) and now have the same issue like @w4cky and @topsirloin.

Accessing the root page of the domain shows a "network error" box
![image](https://user-images.githubusercontent.com/73472903/145236461-28df446b-d69f-411c-969e-e1555dcf1e35.png)

The web interface tries to load isLoggedIn on the API which fails with error 500.
![image](https://user-images.githubusercontent.com/73472903/145236658-5995e1dc-a71b-4a65-b0a3-8e4b06d82f08.png)

I append the Apache error log as screenshot as the text messes up:
![image](https://user-images.githubusercontent.com/73472903/145236912-aebfda9c-3cfa-4426-9824-118834072395.png)

Maybe @davidbolvansky has an idea? Thanks in advance!

**Comment by davidbolvansky** [comment]
I think that you have quite new version of python flask.

We are working on some updates and fixes so maybe you can try “master-next” branch?

**Comment by cmprmsd** [comment]
Yes flask was the issue / at least part of it.

```
pip3 install flask==0.10.0
systemctl restart apach2
```

did help. Now I can load the UI.

After connecting now I get the UI, can login and then there is another error telling me that my authorization is not correct although the UI accepted the login. Maybe the backend has different credentials.
![image](https://user-images.githubusercontent.com/73472903/145244606-38a97ac1-cd91-4c40-8ecc-85e2cec670c2.png)

Sure thing! 
I'll try the branch you proposed :)

**Comment by cmprmsd** [comment]
I did not have the time to begin from start, so I just switched the master-next branch and reinstalled all packages. However, the after restarting apache2 (which works without errors) I cannot connect to either 80 or 5000. 🤷‍♂️

**Comment by roman4ello** [comment]
Thank you @cmprmsd ! 
It works with `flask==0.10.0`.
Error is gone.

**Comment by davidbolvansky** [comment]
So.. closed.
