### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Are-s-h** [nesfit/fitcrack#18]
Hello, first of all thanks for the great project!

I installed everything under ubuntu 18.04 without an error message. 
When I call up 127.0.0.1 to start Fitcrack, the red message "Network Error" appears.
What can be the problem?
Thanks HG

**Comment by davidbolvansky** [comment]
Maybe check https://github.com/nesfit/fitcrack/issues/17 if master-next would work for you.

**Comment by dis0wned** [comment]
I am running into the same network error. The installation succeeded, the API is up and accessible, but I can not access the webadmin - I continue to get the red Network error prompt. I followed the steps in #17 but it did not resolve the issue. Any other suggestions how to resolve this.

**Comment by HashGov** [comment]
1) uninstall
2) git clone https://github.com/nesfit/fitcrack.git --branch master-next
3) pip3 install flask==0.10.0
    systemctl restart apache2
4) Install Fitcrack 
5) When asked: Port 80 (yes) and then answer the next question with (yes)

Worked well. 
Regards

**Comment by dis0wned** [comment]
I just went through all steps and I have the same outcome. I'm scratching my head. Not one error during the install

**Comment by dis0wned** [comment]
Re-ran the install and updated the daemons, these are the errors I got 
Build successful.
Starting Fitcrack server again...
Traceback (most recent call last):
  File "./bin/start", line 757, in <module>
    config = configxml.ConfigFile(config_filename).read()
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 131, in read
    raise Exception("Couldn't parse XML config\n")
Exception: Couldn't parse XML config

Traceback (most recent call last):
  File "./bin/status", line 757, in <module>
    config = configxml.ConfigFile(config_filename).read()
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 131, in read
    raise Exception("Couldn't parse XML config\n")
Exception: Couldn't parse XML config

Server daemons updated and started :-)
All done.

**Comment by dis0wned** [comment]
Also ran through updating the apache server 
WebAdmin update done. Restarting Apache...
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
Done.

**Comment by davidbolvansky** [comment]
Try dev branch. 

Closed. Reopen if not working for you.
