### ISSUE TITLE
Automatically job

### ISSUE THREAD

**Issue by Are-s-h** [nesfit/fitcrack#22]
Is it possible that all new host automatically get a started job? 
Or do I have to add the host manually always? 
thx

**Comment by ihranicky** [comment]
Currenty, hosts need to be assigned manually. This may be an interesting optional feature for future updates, but the questions is - what to do if there are multiple jobs running? To which one the host should be added?You can add a host to multiple jobs, but it will do sort of round-robin assignment, as a single host can only work on a single job at a time.

If you want to automate adding hosts, you can create a custom-defined trigger in the database.

The inspiration can be `new_host_trigger` in:
https://github.com/nesfit/fitcrack/blob/master/server/sql/20_create_triggers.sql
Essentially, adding a single line `fc_host_activity` should be enough. 

(The detailed meaning of the tables is described in https://fitcrack.fit.vutbr.cz/files/doc/TR_Fitcrack_architecture.pdf, page 74)

**Comment by HashGov** [comment]
The automatic host-add would be a great feature, because when many people participate in the project would be easier handling. The automatic assignment could be done by random or a priority setting maybe?!

I read page 74 and looked at the "20_create_triggers.sql." I have not quite understood where the line is to be inserted. Can you show an example?
Thx

**Comment by soxrok2212** [comment]
+1 on priority based automatic tasking!

**Comment by davidbolvansky** [comment]
Please try our dev branch, implemented.

In System -> Settings there is a new option "Add new hosts to running jobs". Default is off. Enable it and save settings. Then, after you add any new host to Fitcrack, this host will be added to running jobs and the host will start doing some cracking work immediatelly.

For priority based automatic tasking - please open new issue and describe this request a bit more.
