### ISSUE TITLE
Live Task Speed

### ISSUE THREAD

**Issue by soxrok2212** [nesfit/fitcrack#26]
Hi, thanks for this software! I'm exploring it as an alternative to Hashtopolis.

I'm wondering if there's functionality to see the current speed of a running task (outside of the benchmark speed in the logs).

Thanks!

**Comment by ihranicky** [comment]
Hello there, currently, we only report live progress on each workunit. But the functionality you describe would be a great and useful improvement, while it is nothing extra difficult to implement. We will consider adding this to the new release that is scheduled for April 22. Thanks for a good tip.

**Comment by davidbolvansky** [comment]
![image](https://user-images.githubusercontent.com/22410393/162280017-95e27392-a7bd-40e7-99d9-94512aff9c92.png)
