### ISSUE TITLE
Upload button missing?

### ISSUE THREAD

**Issue by Allesanddro** [nesfit/fitcrack#29]
BRANCH:DEV
CONFIG:DEFAULT
Ubuntu20.04 x64
I tried to upload a hashlist but it seems the button is missing or am I doing something wrong?

![image](https://user-images.githubusercontent.com/23656101/158758129-ab7c91da-10fe-4437-8f40-6a20889ef3aa.png)

**Comment by OviOvocny** [comment]
You don't actually upload the hash list, it's read client-side immediately as you pick the file. You're doing it right, it's just broken. Thanks for bringing it up.

**Comment by Allesanddro** [comment]
Alright then imma provide this aswell 

`TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at o.hashFileSelected (addJobView.dfa72a87.js:7:60)
    at Ur (vendor.6aa46313.js:5:11776)
    at o.r (vendor.6aa46313.js:5:13640)
    at Ur (vendor.6aa46313.js:5:11776)
    at o.Vy.e.$emit (vendor.6aa46313.js:5:26708)
    at o.fileChange (fileUploader.f3de9567.js:1:1809)
    at Ur (vendor.6aa46313.js:5:11776)
    at o.r (vendor.6aa46313.js:5:13640)
    at Ur (vendor.6aa46313.js:5:11776)
    at o.Vy.e.$emit (vendor.6aa46313.js:5:26708)
Eh @ vendor.6aa46313.js:5
vh @ vendor.6aa46313.js:5
qi @ vendor.6aa46313.js:5
Ur @ vendor.6aa46313.js:5
r @ vendor.6aa46313.js:5
Ur @ vendor.6aa46313.js:5
Vy.e.$emit @ vendor.6aa46313.js:5
fileChange @ fileUploader.f3de9567.js:1
Ur @ vendor.6aa46313.js:5
r @ vendor.6aa46313.js:5
Ur @ vendor.6aa46313.js:5
Vy.e.$emit @ vendor.6aa46313.js:5
set @ vendor.6aa46313.js:14
onInput @ vendor.6aa46313.js:14
Ur @ vendor.6aa46313.js:5
r @ vendor.6aa46313.js:5
n._wrapper @ vendor.6aa46313.js:5`

**Comment by OviOvocny** [comment]
Ok, this should be fixed in dev now. If it works for you, I think we can close this.

**Comment by Allesanddro** [comment]
Well if I try to import a hashlist (300mb) ~1.3 mio hashes the memory usage of chrome goes up to 6gb and then crashes with the error out of memory

**Comment by Allesanddro** [comment]
I mean it works for small hashlists.
Is it possible to add an import option like for the wordlists?

**Comment by OviOvocny** [comment]
That is a bit more complex (reading large files, validating the hashes, ...) and beyond the scope of this issue. I'm closing this as the file reader bug has been fixed. Feel free to open another one to discuss the large hash list issue.

**Comment by davidbolvansky** [comment]
You are right, big hashlists cause significant problems for fitcrack (afaik hashtopolis as well) currently as things were designed for small hashlists/single hash.

Major redesign/rework required.
