### ISSUE TITLE
Enable or disable worker/agent from web control panel

### ISSUE THREAD

**Issue by soxrok2212** [nesfit/fitcrack#31]
Hi!

Another feature I didn't see, is it possible to enable or disable an agent from the admin page without going to each machine running the BOiNC client? AKA stop it from tasking if there is any available or if it is assigned to one.

**Comment by davidbolvansky** [comment]
Yeah, we have "Show or hide" (host) but we dont have something like "Unassign from all jobs".

**Comment by davidbolvansky** [comment]
![image](https://user-images.githubusercontent.com/22410393/173925150-79ea5222-2bdf-4786-be27-8d1569a794b0.png)

in dev branch now.
