### ISSUE TITLE
feat req: Local Caching for Large Dictionaries?

### ISSUE THREAD

**Issue by lachlan2k** [nesfit/fitcrack#33]
Hi!

We're currently evaluating distributed cracking software for a new password cracking cluster we are building.

We really like almost everything Fitcrack has to offer, however we're running into a massive network bottleneck for dictionary based attacks.

We use 100GB+ dictionaries, and only have 1gbps networking between the 3 nodes. Because of this, we are estimating that the chunking method used by Fitcrack will massively bottleneck our performance, especially for algorithms like NTLM where we might have >500GH/s per node.

Would it be possible to implement an option to store a full copy of the dictionary on every worker, and perform the chunking on the workers, similar to hashtopolis works? This would be a game changer for us and put Fitcrack back on the table as a viable option.

Thanks
🙏

**Comment by davidbolvansky** [comment]
Hello,

Yes, this alternative distribution strategy makes sense to me. I will try to implement it.

**Comment by davidbolvansky** [comment]
Hello,

So I have a first working prototype. 

I would like to ask you if following solution work for you and makes sense to you (my opinion is biased:) ):

1. in web UI, you will have a new option like "distribution mode" to switch between fragmenting (chunking) on server or fragmenting on host. On server is this current behaviour, on client is this new distribution mode.
2. My first prototype uses "config" file on host, at the moment just named "/etc/fitcrack_dict.json" where we have mappings between dict file names and real paths on the host.

Example:
```
{
  "bible.txt" :  "/usr/share/collections/dictionaries/bible.txt",
  "english.txt" : "/usr/share/collections/dictionaries/english.txt",
  "myspace.txt" : "/usr/share/collections/dictionaries/myspace.txt",
  "darkweb2017-top1000.txt" : "/usr/share/collections/dictionaries/darkweb2017-top1000.txt"
}
```

So once we find a real path to the required dictionary, we use hashcat options --skip/--limit to compute certain fragment of the dictionary.

**Comment by lachlan2k** [comment]
Wow, that was fast!

Yes, that sounds excellent. I would imagine other people might like it for Fitcrack to automatically download any missing dictionaries? However I don't need that for my use case, and the JSON config sounds perfect for me.

Is there a branch somewhere I can check out this prototype?

Thanks once again,
Lachlan

**Comment by davidbolvansky** [comment]
Yeah. I would probably upstream a version where the whole dictionary is downloaded once per host (shared between jobs on that host).

That “json mapping” version could be useful if you want to copy it manually and to avoid that one download step. Leave it? Ditch it?

The branch will come out soon.

**Comment by lachlan2k** [comment]
I'm not too bothered either way. If Fitcrack downloads it automatically when it is first needed, that would be fine for me too :)

**Comment by davidbolvansky** [comment]
>  If Fitcrack downloads it automatically when it is first needed

Ok, yeah. So this variant will be added (some cleanup and testing is still needed, but no longer than few days).

**Comment by davidbolvansky** [comment]
![image](https://user-images.githubusercontent.com/22410393/166163721-89b15633-d698-4dbd-b9fc-dfc36b2fb6cb.png)

**Comment by davidbolvansky** [comment]
Please try branch fragmenting_on_hosts

**Comment by lachlan2k** [comment]
I'll give this a go this week :)

**Comment by davidbolvansky** [comment]
Any news?

**Comment by lachlan2k** [comment]
Hi, sorry for the delay in replying! I was going to test this in my lab a few weeks ago, but I was sick that weekend.
We're just building a brand new cracking cluster this week, so I'll hopefully be testing tomorrow and will get back to you!

Thanks once again.

**Comment by lachlan2k** [comment]
Hey! Just testing this just now.

I've got a slight issue, work_generator doesn't want to start:
```
boincadm@bomba:~/projects/fitcrack/log_bombe[boincadm@bombe log_bombe]$ tail work_generator.log
2022-06-09 10:40:05.3853 [CRITICAL] can't read input template templates/dict_alt_in
[2022/06/09 11:15:53] Executing command: work_generator -d 3 --app fitcrack
09.06.2022 11:15:54 Starting Fitcrack WorkGenerator ...
2022-06-09 11:15:54.2506 [CRITICAL] can't read input template templates/dict_alt_in
[2022/06/09 11:16:58] Executing command: work_generator -d 3 --app fitcrack
09.06.2022 11:16:58 Starting Fitcrack WorkGenerator ...
2022-06-09 11:16:58.5111 [CRITICAL] can't read input template templates/dict_alt_in
[2022/06/09 11:19:02] Executing command: work_generator -d 3 --app fitcrack
09.06.2022 11:19:02 Starting Fitcrack WorkGenerator ...
2022-06-09 11:19:02.4720 [CRITICAL] can't read input template templates/dict_alt_in
```

It seems like `template/dict_alt_in` doesn't exist?

Looking forward to hearing from you! Thanks.

**Comment by lachlan2k** [comment]
Seems to work great for me! Happy to have this merged to dev when you are.

**Comment by davidbolvansky** [comment]
Could you also try dict attack with rules? If everything works for you..

**Comment by lachlan2k** [comment]
Yep, I tried both dict and dict+rules. I tried both on a 2-node setup and a 3-node setup.

**Comment by davidbolvansky** [comment]
Ok, thanks, I will merge it soon.
