### ISSUE TITLE
Jobs in my fitcrack not working

### ISSUE THREAD

**Issue by Dkyuu** [nesfit/fitcrack#34]
I install fitcrack on Ubuntu 18.04 following this guide https://github.com/nesfit/fitcrack
I can create job on webadmin but when I launch it there is no process.
please give me instructions for this problem
Thanks

**Comment by davidbolvansky** [comment]
I suggest you to use dev branch & Ubuntu 20.04 atleast.

**Comment by Dkyuu** [comment]
After installed, I have a problem:  The browser (or proxy) sent a request that this server could not understand. 
How to I fix it? 
Thanks

**Comment by davidbolvansky** [comment]
You need to use / install flask 2.0.3 or older :( fc not yet compatible with 2.1.0.

**Comment by Dkyuu** [comment]
I installed flask 2.0.3 but it still gives me the above error.

**Comment by poli-cz** [comment]
You also need to ensure that you have Werkzeug==2.0.3. It is now fixed in webadmin requirements.txt

**Comment by Dkyuu** [comment]
Thank you, I have fixed this error. However when I creating the job and run it, still no process starts. what should I do?

**Comment by davidbolvansky** [comment]
Okey, so lets try it for example with "sample-dict-md5-quick" (known working and small job).

Have you assigned this host to your job? Is your host online?

**Comment by Dkyuu** [comment]
![image](https://user-images.githubusercontent.com/105628005/168769239-d64edfd2-34f9-42b8-b4ab-a49010022d7e.png)

**Comment by Dkyuu** [comment]
![image](https://user-images.githubusercontent.com/105628005/168770231-7ad48929-8a9e-4c61-8a30-9a381f335d19.png)

**Comment by Dkyuu** [comment]
What's wrong here?

**Comment by davidbolvansky** [comment]
Stop everything and start "sample-dict-md5-quick". After a few minutes of "running" it should end as "finished".

Otherwise, open your job, scroll to workunits, click on "Log" so you see something like:
![image](https://user-images.githubusercontent.com/22410393/168771137-9718a77f-db61-4707-9291-57bf058c03fa.png)

and upload your log here.

**Comment by Dkyuu** [comment]
![image](https://user-images.githubusercontent.com/105628005/168772055-8625ba26-c11d-4f12-8062-eee2e3c10642.png)

**Comment by Dkyuu** [comment]
maybe I did something wrong, the steps I followed are the following instructions:
https://github.com/nesfit/fitcrack/tree/dev
https://github.com/nesfit/fitcrack/tree/dev/webadmin     ( I don't have npm installed)

**Comment by davidbolvansky** [comment]
Click on 'v' to show logs. Upload them here. We really cannot help you just by looking on screenshots.
![image](https://user-images.githubusercontent.com/22410393/168773414-7a3b3c24-4114-441a-815d-89aaa0960a5f.png)

**Comment by Dkyuu** [comment]
![image](https://user-images.githubusercontent.com/105628005/168773984-8918ba2a-702a-48f9-b535-4a7bc73d5b0c.png)

**Comment by davidbolvansky** [comment]
Gosh.
Full logs, please.  Copy everything to txt file and upload txt file here.

**Comment by Dkyuu** [comment]
I'm sorry, it's here
[a.txt](https://github.com/nesfit/fitcrack/files/8706904/a.txt)

**Comment by davidbolvansky** [comment]
` what() : Hashcat failed to run! Exit code: -1. ATTENTION! No OpenCL, Metal, HIP or CUDA installation found.`

You need to install proper drivers for your GPU. There are many manuals how to do it, for example:

https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-ubuntu-20-04-focal-fossa-linux

if you have NVIDIA GPU.

**Comment by Dkyuu** [comment]
oh, thank you so much

**Comment by Dkyuu** [comment]
How do I adjust the execute sequence?

**Comment by Dkyuu** [comment]
![image](https://user-images.githubusercontent.com/105628005/170160861-714e7d91-c8fb-467d-98b7-186c96e8d710.png)

**Comment by davidbolvansky** [comment]
https://github.com/nesfit/fitcrack/tree/dev

See “Advanced: Host specific configuration” section in README
