### ISSUE TITLE
Computation error (BOINC)

### ISSUE THREAD

**Issue by thegnomedesu** [nesfit/fitcrack#36]
When running large keyspace across 20+ systems I have noticed that a lot of hosts start producing "computation error" which then stops the job completing

For example i hashed "password" into NTLM, then setup a bruteforce clients start failing at 95% at keyspace 95

The bruteforce was done from 1-8 length special/upper/lower/number (?a) with 3D markov and without markov

The client log says "invalid hex character detected in mask"

**Comment by thegnomedesu** [comment]
Full logs attached.
[fitcrack logs.txt](https://github.com/nesfit/fitcrack/files/8786592/fitcrack.logs.txt)

**Comment by davidbolvansky** [comment]
What about "?l?l", works for you? 

?l?l works for me, but ?a?a is somehow broken for me as well, some weird mask hc keyspace 1....

**Comment by davidbolvansky** [comment]
Pushed https://github.com/nesfit/fitcrack/commit/d372bb1ba495a8f70b739a6473d30da790dac39f to fix issue I observed above.

Please, try again.

**Comment by davidbolvansky** [comment]
Ok, I think https://github.com/nesfit/fitcrack/commit/b1c61db2c2ffa9d0af34d5c88bc422c3c2e21201 will fix this issue for you.

**Comment by davidbolvansky** [comment]
I will close this issue.

Please reopen if the commited fix does not work  for your issue.

**Comment by thegnomedesu** [comment]
Looks like this is still an issue when doing ?a?a
[boinc.txt](https://github.com/nesfit/fitcrack/files/9314425/boinc.txt)
