### ISSUE TITLE
Work_generator bottleneck

### ISSUE THREAD

**Issue by thegnomedesu** [nesfit/fitcrack#37]
Hello all,

During some of our testing I have noticed that we are actually completing fragment jobs with the Weakpass 3a dictionary faster than the work generator can actually make the job for clients, is their anything we can do to speed up the work generator? looking at htop and glances it appears that it only uses 1 cpu thread, can this be changed?

**Comment by davidbolvansky** [comment]
Dictionary attack?

At first, please check https://github.com/nesfit/fitcrack/issues/33

Maybe that alternative distribution mode (on client) may help you. (No splitting on server, no huge i/o).

**Comment by thegnomedesu** [comment]
Hello yes it is a dictionary attack, we are not running into issues with disk/network I/O however the job creator cant make work units fast enough for 20+ systems on large dictionaries. The bottleneck I am seeing is with the process "Work_Generator"

**Comment by davidbolvansky** [comment]
try branch fragmenting_on_hosts as mentioned in https://github.com/nesfit/fitcrack/issues/33

As there is no fragment creation on server side, I would expect faster work generation.

Parallel work generator of workunits from various jobs could be probably easy to do, but parallel generation of workunits of same job is a different story.


Maybe you can also change “Seconds per workunit” to create smaller/larger workunits, as you wish.

**Comment by thegnomedesu** [comment]
Changing branches before has caused me to have to essentially reinstall everything, is their an easy way to switch to this other branch? We are currently using the latest DEV branch and going from the April DEV branch to May DEV caused me to have to re-setup the project on every host under my control which took quite an amount of time.

**Comment by davidbolvansky** [comment]
No there is no easy way :(

Jobs can be exported via web gui.

Hosts are pain, yes. But with https://github.com/nesfit/fitcrack/blob/dev/installer/boinc_connect.py you can automatize it a bit.

**Comment by thegnomedesu** [comment]
How would you go about automating it? I've looked at what you linked but i'm unsure what you mean.

**Comment by davidbolvansky** [comment]
BTW, I think that we could use C api to write fragments instead of C++ expensive ofstreams.

**Comment by davidbolvansky** [comment]
https://github.com/nesfit/fitcrack/commit/45a3420b4c3e019d04aa47699c9ebb117693b315 should significantly speedup dictionary fragmentation

**Comment by davidbolvansky** [comment]
But I see the bottleneck - https://github.com/nesfit/fitcrack/blob/dev/server/src/source/Utils/InputDict.cpp#L77

For dict like weakpass, skiping majority of new lines may take some minutes. Let me see if we call use seekg/tellg to our advantage here.

**Comment by davidbolvansky** [comment]
https://github.com/nesfit/fitcrack/commit/9ebca66d9e9c94c4163a56436f7e9466b1a2da25 should fix bottlenecks in the generator with very huge dictionaries.

Parallel workunit generator from different jobs could still be done, but not sure if worth it as this commit should fix major problems.

I will close this issue. Try with dev or master branch if you want. If bottlenecks are still there, create new issue with exact steps how to reproduce it and you local measurements. Thanks.
