### ISSUE TITLE
Flask Secret Key is Statically Defined

### ISSUE THREAD

**Issue by lachlan2k** [nesfit/fitcrack#41]
Flask is currently configured with a static value for `SECRET_KEY`. This means that every Fitcrack installation shares the same, known, secret key. This creates a security vulnerability, as this key is (per its name) to be kept secret, as it is used for signing cookies, JWTs, etc.

https://github.com/nesfit/fitcrack/blob/86d5986e5f9c36bc1e164082d243c3967ca01b22/webadmin/fitcrackAPI/src/app.py#L49

I would suggest that the key should either be stored in a config file, and randomly generated or installation, or, preferably, generated fresh every time the server is started:
```py
import secrets
# .........
     flask_app.config['SECRET_KEY'] = secrets.token_hex(16)
```

Interested in your thought :) I'm happy to make a PR once a solution is agreed upon.

**Comment by davidbolvansky** [comment]
'secrets.token_hex(16)' sounds good.

What do you think @ihranicky @OviOvocny ?

**Comment by davidbolvansky** [comment]
Thanks for the patch. Closed.
