### ISSUE TITLE
Trickler Crashes due to Integer Overflow & Other SQL Concerns

### ISSUE THREAD

**Issue by lachlan2k** [nesfit/fitcrack#45]
Hi,

On one of my test workstations, the integrated intel graphics reports utilization and temperature of -1. This causes the trickler process to die, as it appears to overflow to 2^64-1 when the database query is made, causing the database query to fail and the program to exit.

```
[2022/06/11 09:31:19] Executing command: trickler --variety fitcrack
2022-06-11 09:31:19.7255  Starting trickle handler
2022-06-11 09:31:19.7269  Got trickle-up message from hostId #2:

      <result_name>fitcrack_1654952461_0_6506_1654952782_0</result_name>
      <time>1654952843</time>
<workunit_name>fitcrack_1654952461_0</workunit_name>
<progress>0</progress>
<total_speed>5030128</total_speed>
<device_1_name>NVIDIA GeForce GTX 1080 Ti</device_1_name>
<device_1_type>GPU</device_1_type>
<device_1_speed>2644704</device_1_speed>
<device_1_temp>57</device_1_temp>
<device_1_util>2</device_1_util>
<device_3_name>Radeon RX 580 Series</device_3_name>
<device_3_type>GPU</device_3_type>
<device_3_speed>2206843</device_3_speed>
<device_3_temp>34</device_3_temp>
<device_3_util>0</device_3_util>
<device_4_name>Intel(R) UHD Graphics 630</device_4_name>
<device_4_type>GPU</device_4_type>
<device_4_speed>178581</device_4_speed>
<device_4_temp>-1</device_4_temp>
<device_4_util>-1</device_4_util>

Succesfully parsed workunit_name: fitcrack_1654952461_0
fc_workunit_id: 0
Succesfully parsed progress: 0
Succesfully parsed total speed: 5030128
Updating workunit progress...
Updating workunit speed...
 fc_device_id 1
Inserting data to fc_device_info...
 fc_device_id 2
Inserting data to fc_device_info...
 fc_device_id 3
Inserting data to fc_device_info...
Database error: Out of range value for column 'temperature' at row 1
query=INSERT INTO `fc_device_info` (`device_id`,`workunit_id`,`speed`,`temperature`,`utilization`) VALUES (3, 0, 178581, 18446744073709551615, 18446744073709551615);
Problem with DB query: INSERT INTO `fc_device_info` (`device_id`,`workunit_id`,`speed`,`temperature`,`utilization`) VALUES (3, 0, 178581, 18446744073709551615, 18446744073709551615);
Shutting down now.
```

These database columns seem to just be signed 32-bit integers, so I think adjusting some types is all that will be necessary to correct this fault.

However, a lot of this code appears like it may be unsafe and possibly vulnerable to SQL injection, for example:
https://github.com/nesfit/fitcrack/blob/83552dbf084f8de37df720fa43e33d6f0370b496/server/src/source/trickler.cpp#L241-L248

If a host maliciously reports itself with the name `foo', ''); ANOTHER_SQL_QUERY_HERE; -- ` it may be able to perform arbitrary SQL commands against the SQL server leading to security issues.

I would suggest killing two birds with one stone and re-writing some of this to use prepared statements, as these provide more type safety, as well as prevent SQL injection attacks.  (https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html, https://dev.mysql.com/doc/c-api/8.0/en/c-api-prepared-statement-interface.html, https://mariadb.com/kb/en/prepared-statement-examples/).

I would offer to help, however unfortunately neither C++ nor SQL are my strong suits :(.

**Comment by davidbolvansky** [comment]
Did you observe this issue with dev branch?

Looking at trickler.cpp in dev branch, this overflow should not happen.
Looking at trickler.cpp in fragmenting_on_hosts branch, there is a possibility of overflow, yeah.
Note: fragmenting_on_hosts is older and meanwhile I fixed many things in dev.



------
>> If a host maliciously reports itself with the name foo', ''); ANOTHER_SQL_QUERY_HERE; -- it may be able to perform arbitrary SQL commands against the SQL server leading to security issues.

In that case, somebody would need to "rename/fake" device name, provided by hashcat.

But generally yes, some code is definitely vulnerable to SQL injection but for this is open source project, it is a very low priority issue for now. (but your second reported security issue looks worse and we need to fix it)

**Comment by lachlan2k** [comment]
Ah, yes, I'm still on fragmenting_on_hosts, didn't realise this was already fixed on dev 😁.

I'll close this for now, but I might make a PR in the next week or two to at least run `mysql_real_escape_string` against user-controllable string inputs. For my installation, all our hosts are trusted so not really an issue for me, but I'd imagine for internet-facing installs with public signups it could be more of a risk.

Thanks once again for your help!
