### ISSUE TITLE
Request: Database updating

### ISSUE THREAD

**Issue by thegnomedesu** [nesfit/fitcrack#47]
Hello,

We have a way to update the web and server side however the database cannot be update as of current. Is their a way to update the sql database?

**Comment by davidbolvansky** [comment]
It depends... mysqldump?

1. create backup with mysqldump
2. install new fitcrack
3. drop database fitcrack
4. restore backup

If there are changes in DB structure, this will not work. 

If you ask for DB migrations, then currently no, as we dont have resources for that.

**Comment by ihranicky** [comment]
Unfortunately, migrations between major versions are currently not supported.

**Comment by davidbolvansky** [comment]
Reopening as we should re-consider this as this is very requested feature.
