### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by nullalloc** [nesfit/fitcrack#48]
I am trying to install fitcrack server on a laptop but I keep encountering an "error during compilation" while installing fitcrack using the automatic installer and selecting option 1(this is the same for option 2).

Laptop specs:
aser Chromebook model:N17Q8
- OS:Ubuntu 22.04 LTS x86_64
- Kernel:5.15.0-40-generic
- CPU:Intel Celeron N3350 (2) @ 2.400GHz
- GPU:Intel HD Graphics 500
- RAM:3806MiB(as reported from neofetch)

What is reported at the end:
`make[2]: *** [Makefile:1748: libboinc_crypt_la-crypt.lo] Error 1
make[2]: Leaving directory '/root/fitcrack-2.3.0/boinc/lib'
make[1]: *** [Makefile:648: all-recursive] Error 1
make[1]: Leaving directory '/root/fitcrack-2.3.0/boinc'
make: *** [Makefile:552: all] Error 2
Error during compilation.
root@server:~/fitcrack-2.3.0#`

Full output:https://pastebin.com/cbp68hrb

Is there something im missing?

**Comment by davidbolvansky** [comment]
Please try dev branch. We will release 2.4.0 soon and 2.3.0 is probably quite broken on newer Ubuntu.

“ Enter the number of compiler threads” - also please follow recommendation and use “1”.

Some time ago @ihranicky tried dev branch with Ubuntu 22 and no issues. Check README in dev branch.

**Comment by nullalloc** [comment]
I removed ubuntu and installed debian 9 on the laptop, using the master branch caused a few errors with mysql so the dev branch was used, I tried installing with docker but whenever I try to bring the project up I get this:

`root@serverA:~# cd fitcrack/
root@serverA:~/fitcrack# docker-compose up
Starting fitcrack_fitcrack_server_1 ... 
Starting fitcrack_fitcrack_server_1 ... error

ERROR: for fitcrack_fitcrack_server_1  Cannot start service fitcrack_server: driver failed programming external connectivity on endpoint fitcrack_fitcrack_server_1 (6ab58031c3af2967b5beefbbfbafa541702c00011cc87fb64493e2438f08e25c): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for fitcrack_server  Cannot start service fitcrack_server: driver failed programming external connectivity on endpoint fitcrack_fitcrack_server_1 (6ab58031c3af2967b5beefbbfbafa541702c00011cc87fb64493e2438f08e25c): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
root@serverA:~/fitcrack#`

I can't find what service might be binding on the same port, what should i be looking for?[Something that might be related? an answer states to stop apache2 from binding/running on port 80?](https://stackoverflow.com/questions/69899466/error-starting-userland-proxy-listen-tcp4-0-0-0-080-bind-address-already-in)

**Comment by ihranicky** [comment]
Hello, it seems something on your host is listening on is already listening on port 80. It is probably Apache/NGINX web server.
Try `netstat -tulpn | grep 80` to find out what it is. If it is Apache then `systemctl stop apache2` (Ubuntu) or `systemctl httpd stop` should resolve the issue.

**Comment by nullalloc** [comment]
stopping apache2 is the solution to my problem.
Thanks to those that helped!
