### ISSUE TITLE
[Docker] .env comments causing issues

### ISSUE THREAD

**Issue by thegnomedesu** [nesfit/fitcrack#51]
Hello,

While trying to setup the Docker version with the comments next to the ports the compose up errors with this:

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.fitcrack_server.ports is invalid: Invalid port "5000"                      # Port for WebAdmin backend (5443 for SSL):5000", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.fitcrack_server.ports is invalid: Invalid port "80"                       # Port for WebAdmin frontend (443 for SSL):80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by thegnomedesu** [comment]
I believe the comments are also related to this:

Starting fitcrack-dev_fitcrack_server_1 ... 
Starting fitcrack-dev_fitcrack_server_1 ... error

ERROR: for fitcrack-dev_fitcrack_server_1  Cannot start service fitcrack_server: driver failed programming external connectivity on endpoint fitcrack-dev_fitcrack_server_1 (ec222fc215c7af5cb2493795bba7995a4284c1e739194e4c515d6b537a617503): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for fitcrack_server  Cannot start service fitcrack_server: driver failed programming external connectivity on endpoint fitcrack-dev_fitcrack_server_1 (ec222fc215c7af5cb2493795bba7995a4284c1e739194e4c515d6b537a617503): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by davidbolvansky** [comment]
>> 0.0.0.0:80: bind: address already in use

The error is clear, port 80 is used.

You need to stop apache or use just use a different port.

@ihranicky do you want to add something?

**Comment by davidbolvansky** [comment]
I followed steps in https://github.com/nesfit/fitcrack/blob/dev/INSTALL-Docker.md#debugging and it works fine for me. 

But looking at https://docs.docker.com/compose/env-file/, yes, it seems we do not follow rules for env file.
I will fix that.

**Comment by davidbolvansky** [comment]
Closed. Reopen if issues still exist.
