### ISSUE TITLE
Compute error

### ISSUE THREAD

**Issue by thegnomedesu** [nesfit/fitcrack#52]
Similar to the issue #36, using ?a?a is causing an issue still. I'm using latest dev version. This was while doing SHA1 hashes
[boinc.txt](https://github.com/nesfit/fitcrack/files/9314440/boinc.txt)

**Comment by davidbolvansky** [comment]
This happens on Windows only but I dont know why. The mask is in quotes so the shell should not expand it.

**Comment by davidbolvansky** [comment]
Probably we could store the mask in hcmask file rather than passing it via command line arguments..

**Comment by davidbolvansky** [comment]
Can you try on Windows after commit https://github.com/nesfit/fitcrack/commit/f9c1050e485fddaeb654ea3b34b7dcad1fb33186 ?

**Comment by thegnomedesu** [comment]
Would this require a full reinstall of fitcrack or a rebuild of the server?

**Comment by davidbolvansky** [comment]
No, this time easier, you can fetch latest dev branch and do:

cd runner
sudo python3 update_binaries.py


The you should see a message that binaries were updated. Then create new job, with this mask and run it.

**Comment by thegnomedesu** [comment]
the python script error'd out with: 
`sudo python3 update_binaries.py 
[sudo] password for c7430a: 
Old version: 1, new version: 2
Created dir: /home/boincadm/projects/fitcrack/apps/fitcrack/2
Building new linux binary
Building new windows binary
/bin/sh: 1: x86_64-w64-mingw32-g++: not found
make: *** [Makefile:45: obj/AttackPCFG.o] Error 127
Traceback (most recent call last):
  File "update_binaries.py", line 58, in <module>
    shutil.copy("./bin/runner.exe", FITCRACK_APPS_DIR + str(last_ver + 1) +
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './bin/runner.exe'
`

**Comment by thegnomedesu** [comment]
installed the missing package now it is running, i have a sha1 brute going now.

**Comment by thegnomedesu** [comment]
Benchmark is now failing to run with:

Invalid hex character detected in mask <soft_link>../../projects/<project>_fitcrack/fitcrack_1660288114_308</soft_link>

**Comment by davidbolvansky** [comment]
It is also possible that update of binaries failed due to first fail with missing mingw gcc.

I suggest:

sudo rm -rf /home/boincadm/projects/fitcrack/apps/fitcrack/2
sudo rm -rf /home/boincadm/projects/fitcrack/apps/fitcrack/3

sudo python3 update_binaries.py

Then try to create and run new job.

**Comment by thegnomedesu** [comment]
Hello, 

I did this and no change yesterday after finding the apps folder, I will send logs when i can.

**Comment by davidbolvansky** [comment]
Ok, so please upload them.

**Comment by davidbolvansky** [comment]
2.4.0 release now in master.

Reopen if you see this issue with release 2.4.0. Semi-updated fitcrack is not supported and we have not time to debug it.

Only official release is supported.
