### ISSUE TITLE
impossible to login with right credentials : an unhandled exception occured

### ISSUE THREAD

**Issue by loiclecapitaine** [nesfit/fitcrack#55]
Hi there,
I have successfully installed fitcrack with no error on my ubuntu 22 server following the providing guide in github.

I can't login in webadmin with default credentials. I have checked the config file of frontend. everything seems to be ok so i don t undestand what i missed !
![2022-10-10_23h04_23](https://user-images.githubusercontent.com/36195094/194952043-c2bb7958-0558-4953-8753-eb262786a631.png)

**Comment by davidbolvansky** [comment]
Show logs, please
/var/log/apache2/error.log

**Comment by loiclecapitaine** [comment]
thanks for reply.
tried with fresh re install. Another error appears "user unknown"
Here is my apache error log :

cat -n /var/log/apache2/error.log 
     1	[Fri Oct 14 18:58:09.410325 2022] [mpm_prefork:notice] [pid 1177] AH00163: Apache/2.4.52 (Ubuntu) mod_wsgi/4.9.0 Python/3.10 configured -- resuming normal operations
     2	[Fri Oct 14 18:58:09.410363 2022] [core:notice] [pid 1177] AH00094: Command line: '/usr/sbin/apache2'
     3	[Fri Oct 14 18:58:44.807876 2022] [wsgi:error] [pid 1247] [remote 127.0.0.1:50728] /usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py:546: SAWarning: relationship 'FcJobStatus.job' will copy column fc_job.id to column fc_job_status.job_id, which conflicts with relationship(s): 'FcJob.status_history' (copies fc_job.id to fc_job_status.job_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="status_history"' to the 'FcJobStatus.job' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
     4	[Fri Oct 14 18:58:44.807918 2022] [wsgi:error] [pid 1247] [remote 127.0.0.1:50728]   mapper = orm.class_mapper(type)
     5	[Fri Oct 14 18:58:44.820331 2022] [wsgi:error] [pid 1247] [remote 127.0.0.1:50728] /usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py:546: SAWarning: relationship 'FcHostActivity.boinc_host' will copy column host.id to column fc_host_activity.boinc_host_id, which conflicts with relationship(s): 'Host.workunits' (copies host.id to fc_host_activity.boinc_host_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="workunits"' to the 'FcHostActivity.boinc_host' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
     6	[Fri Oct 14 18:58:44.820354 2022] [wsgi:error] [pid 1247] [remote 127.0.0.1:50728]   mapper = orm.class_mapper(type)
     7	[Fri Oct 14 18:58:44.824648 2022] [wsgi:error] [pid 1247] [remote 127.0.0.1:50728] /usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py:546: SAWarning: relationship 'FcUserPermission.job' will copy column fc_job.id to column fc_user_permissions.job_id, which conflicts with relationship(s): 'FcJob.permission_records' (copies fc_job.id to fc_user_permissions.job_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="permission_records"' to the 'FcUserPermission.job' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
     8	[Fri Oct 14 18:58:44.824667 2022] [wsgi:error] [pid 1247] [remote 127.0.0.1:50728]   mapper = orm.class_mapper(type)

**Comment by davidbolvansky** [comment]
Maybe recent fix could help you https://github.com/nesfit/fitcrack/commit/c172372c5f95fca54510144be387c5c4264df1cd

**Comment by loiclecapitaine** [comment]
HiThanks for advise but my file was already like that. So I made a fresh install and set mysql with mysql_secure_installation and it works now. I think it was a problem of autorisation access database. Regards Loic Lecapitaine -------- Message original --------De : Dávid Bolvanský ***@***.***>Date : ven. 14 oct. 2022 à 20:45À : nesfit/fitcrack ***@***.***>Cc : Lolodesbois ***@***.***>, Author ***@***.***>Objet : Re: [nesfit/fitcrack] impossible to login with right credentials : an unhandled exception occured (Issue #55)
Maybe recent fix could help you c172372
