### ISSUE TITLE
Is it possible to run Fitcrack on an intranet and without internet?

### ISSUE THREAD

**Issue by hoten1701** [nesfit/fitcrack#57]
Due to some requirements I need to deploy Fitcrack on an intranet, without internet. Can you help me?

**Comment by ihranicky** [comment]
Hello, yes, but for the installations you may need access to certain repositories that are online. Same for the drivers on the client nodes. We also plan to release a pre-build docker image for the server which should make server installation easier.

**Comment by davidbolvansky** [comment]
pre-build docker image was released.

https://github.com/nesfit/fitcrack/blob/master/INSTALL-Docker.md

Please reopen if you need additional help.

**Comment by Dkyuu** [comment]
thanks, but i have problem with boinc. Specifically, I am unable to connect the boinc server to the boinc clients. Can you give me some advice?
