### ISSUE TITLE
I can't install folowwing provided guide

### ISSUE THREAD

**Issue by GraverErmitage** [nesfit/fitcrack#58]
Hi Team,

Please have a look.
I did all listed here https://github.com/nesfit/fitcrack/blob/master/INSTALL-Installer.md#instubu22
Then I created a folder, make a git clone, and start 
![image](https://user-images.githubusercontent.com/34091165/204057240-fef52878-5949-4ce1-bbac-f1472adac84f.png)

**Comment by davidbolvansky** [comment]
It seems you miss submodule boinc, so try:


`git clone --recursive https://github.com/nesfit/fitcrack`

**Comment by GraverErmitage** [comment]
Hello! Thank you it moved me forward but not so far. Now I tried about 6-7 times to reinstall Ubuntu 22.04 LTS and checked with different passwords. No one works well here. I have always an issue at this step.
![image](https://user-images.githubusercontent.com/34091165/204924077-ed29f849-4bc1-40f6-be70-2471007be552.png)

**Comment by davidbolvansky** [comment]
/install_fitcrack.sh in a root terminal is not a first thing to do, maybe this could be a problem here.

Check
https://github.com/nesfit/fitcrack/blob/master/INSTALL-Installer.md#instubu22

There are some steps which needs to be done before install_fitcrack.sh

@ihranicky wrote manual for Ubuntu 22.04.

**Comment by GraverErmitage** [comment]
@davidbolvansky Thank you. Of course, I did all steps as described in the guide for 22.04 LTS. Just let me know did you try to do it in the OS and by following to provided steps. Every day I install the OS from scratch and do the steps. Still no success. Please make a video of how you do it and place it on the youtube channel. It will be very useful. But please try to don't use standard passwords, but some easy passwords. Thank you in advance.

**Comment by ihranicky** [comment]
@GraverErmitage Hi, it seems, the installer failed to add DB triggers under the fitcrack user. This happened because a global var was reset after reboot. Okay, I think I found a solution...

At the MySQL installation, instead of:
`mysql> SET GLOBAL log_bin_trust_function_creators = 1;`
try:
`mysql> SET PERSIST log_bin_trust_function_creators = 1;`

This should fix your problem. Please, tell us if that worked.
