### ISSUE TITLE
Feature request: Set priority of jobs

### ISSUE THREAD

**Issue by MrCracky** [nesfit/fitcrack#59]
1) What hardware requirements (RAM, CPU, HD) does my server need if I want to run about 500 hosts? 
Is there a bottleneck or are the hosts unlimited in number?

2) Adding hosts automatically is great! It would be great if I could prioritize the individual jobs. For example with a selection button between 1-3. At "1" 50% of the next 10 new hosts are assigned to the job. At "2" 30% and at "3" 20%. So you could prioritize the jobs better when new hosts sign up.

**Comment by pluskal** [comment]
Hi @MrCracky, in case you are still interested in distributed password cracking, I may be able to provide a consultation on this topic. 

You can drop me an email on pluskal at netsearch.cz

**Comment by davidbolvansky** [comment]
Regarding second question: I agree that such feature would be useful, but we probably a more general solution. Generally, a prioritization is a big open area.

**Comment by davidbolvansky** [comment]
Option to set priority added in dev.

![image](https://github.com/nesfit/fitcrack/assets/22410393/fd481cfe-3ba8-4723-ad61-4aa0b69f2c14)
