### ISSUE TITLE
I have the same issue as #14 - please help to solve

### ISSUE THREAD

**Issue by GraverErmitage** [nesfit/fitcrack#60]
Hello,

I have the same case as https://github.com/nesfit/fitcrack/issues/14
I did as mentioned here https://nesfit.github.io/fitcrack/#/guide/hosts?id=using-the-command-line
But step 4. never happens (That's all, your host will soon appear in Webadmin)
I am in the server http://static.ip_address.clients.your-server.de/hosts and the list is always empty.

BR

**Comment by davidbolvansky** [comment]
Try to run this script

https://github.com/nesfit/fitcrack/blob/master/installer/boinc_connect.py

if any error, please share detailed output.

**Comment by ihranicky** [comment]
@GraverErmitage Did this help?

**Comment by GraverErmitage** [comment]
Hi! Sorry, I didn't have time to check. Please mark it as possible solved. When I will try to set up the system next time I will come back to the thread.
