### ISSUE TITLE
Can not load http://ip/fitcrack/server_status.php?xml=1

### ISSUE THREAD

**Issue by ermolushka** [nesfit/fitcrack#61]
Hello. I installed Fitcrack manually, everything seems to work but on UI I can see error

`Can not load http://my-ip/fitcrack/server_status.php?xml=1`

Do you know how to solve it? Also, not sure how to connect from headless client as keep on getting `Authorization failure: -155`, maybe it is related.

**Comment by davidbolvansky** [comment]
Try dev branch

**Comment by Yamanipanuchi** [comment]
I tried the Dev branch here with same result.

`[Tue Jan 17 14:14:23.375958 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] [2023-01-17 14:14:23,371] ERROR in app: Exception on /serverInfo/info [GET]
[Tue Jan 17 14:14:23.376075 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] Traceback (most recent call last):
[Tue Jan 17 14:14:23.376303 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/serverInfo/server.py", line 44, in get
[Tue Jan 17 14:14:23.376311 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     response = urllib.request.urlopen(request)
[Tue Jan 17 14:14:23.376314 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
[Tue Jan 17 14:14:23.376316 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     return opener.open(url, data, timeout)
[Tue Jan 17 14:14:23.376746 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/lib/python3.10/urllib/request.py", line 525, in open
[Tue Jan 17 14:14:23.376789 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     response = meth(req, response)
[Tue Jan 17 14:14:23.377357 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
[Tue Jan 17 14:14:23.377450 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     response = self.parent.error(
[Tue Jan 17 14:14:23.377461 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/lib/python3.10/urllib/request.py", line 563, in error
[Tue Jan 17 14:14:23.377477 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     return self._call_chain(*args)
[Tue Jan 17 14:14:23.377508 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
[Tue Jan 17 14:14:23.378540 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     result = func(*args)
[Tue Jan 17 14:14:23.378552 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
[Tue Jan 17 14:14:23.378566 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     raise HTTPError(req.full_url, code, msg, hdrs, fp)
[Tue Jan 17 14:14:23.378570 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] urllib.error.HTTPError: HTTP Error 500: Internal Server Error
[Tue Jan 17 14:14:23.378574 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] 
[Tue Jan 17 14:14:23.378577 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] During handling of the above exception, another exception occurred:
[Tue Jan 17 14:14:23.378580 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] 
[Tue Jan 17 14:14:23.378583 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] Traceback (most recent call last):
[Tue Jan 17 14:14:23.378586 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Tue Jan 17 14:14:23.378590 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     rv = self.dispatch_request()
[Tue Jan 17 14:14:23.378593 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
[Tue Jan 17 14:14:23.378597 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue Jan 17 14:14:23.378600 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/api.py", line 404, in wrapper
[Tue Jan 17 14:14:23.378603 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     resp = resource(*args, **kwargs)
[Tue Jan 17 14:14:23.378606 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 84, in view
[Tue Jan 17 14:14:23.378610 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
[Tue Jan 17 14:14:23.378613 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/resource.py", line 46, in dispatch_request
[Tue Jan 17 14:14:23.378617 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     resp = meth(*args, **kwargs)
[Tue Jan 17 14:14:23.378620 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/marshalling.py", line 244, in wrapper
[Tue Jan 17 14:14:23.378623 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     resp = f(*args, **kwargs)
[Tue Jan 17 14:14:23.378626 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/serverInfo/server.py", line 46, in get
[Tue Jan 17 14:14:23.378630 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     abort(500, 'Can not load ' + url)
[Tue Jan 17 14:14:23.378633 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/flask_restx/errors.py", line 28, in abort
[Tue Jan 17 14:14:23.378636 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     flask.abort(code)
[Tue Jan 17 14:14:23.378639 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py", line 941, in abort
[Tue Jan 17 14:14:23.378643 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     _aborter(status, *args, **kwargs)
[Tue Jan 17 14:14:23.378657 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]   File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py", line 924, in __call__
[Tue Jan 17 14:14:23.378661 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208]     raise self.mapping[code](*args, **kwargs)
[Tue Jan 17 14:14:23.378664 2023] [wsgi:error] [pid 295] [remote 192.168.1.230:50208] werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
`

Get this error in my log files each time the erorr shows up on the web interface.

**Comment by ermolushka** [comment]
With manual installation it works. The issue is with permissions of some folder.
