### ISSUE TITLE
Failed upload of dictionary leaves ghost orphan that is not shown in Webadmin, causing issues

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#67]
Hello. I found this issue in tandem with issue #66. When I try to create a dictionary that has an issue, Fitcrack rejects this and shows an error message (as expected). However, when I then try to upload the dictionary (or any dictionary with the same name) again, a "File with name buggy_dict.txt already exists. Path: /usr/share/collections/dictionaries/buggy_dict.txt" error message is shown. Since the original faulty dictionary was only half added to Fitcrack—that is to say that the file exists in `/usr/share/collections/dictionaries/` but is not in the database and thus not shown in Webadmin—a dictionary with the same name can never be added again (unless one has access to the server Fitcrack is running on and removes the orphan file).

I identified that the issue stems from this part of code

https://github.com/nesfit/fitcrack/blob/91fd2ecd461f699c0b05aff2a301c1ae6f805045/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/dictionary/dictionary.py#L146-L193

Concretely, on this line

https://github.com/nesfit/fitcrack/blob/91fd2ecd461f699c0b05aff2a301c1ae6f805045/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/dictionary/dictionary.py#L161

the uploaded file is saved to `/usr/share/collections/dictionaries/` but in the case of any issue with the file, no cleanup of the created file is performed, causing an orphan file to be left behind that causes the described issues.

### System details
Fitcrack dev build (f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057) on Ubuntu 22.04.2

### How to reproduce
1. In Webadmin, go to Library -> Dictionaries
2. Perform a faulty upload (for example the one described in issue #66).
3. The dictionary has not been added to the list of dictionaries as shown in Webadmin
4. Try to upload the dictionary (or any dictionary with the same name) again
5. Webadmin will show a "File with name buggy_dict.txt already exists. Path: /usr/share/collections/dictionaries/buggy_dict.txt"

**Comment by davidbolvansky** [comment]
I will check it, thanks

**Comment by OviOvocny** [comment]
@alpatron could you try it with the hotfix branch from the linked PR? I concluded that I would certainly die if I tried to make Fitcrack run on ARM or a remote VM just to test two lines of code, so I must delegate.

**Comment by OviOvocny** [comment]
should be okay now
