### ISSUE TITLE
Uploading certain types of resource files fails if filename was used in the past

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#68]
Hi. If I try to add a Markov file or a mask set with a filename that was used in the past but has since been deleted[^1], the upload fails with a "File with name test_add.hcmask already exists. Path: /usr/share/collections/masks/test_add.hcmask" error. This behaviour only happens with Markov files and mask sets; other resource files in the Library tab (dictionaries, PCFGs, rules, and charsets) do not exhibit this behaviour.

From what I can see, the problem happens because the code for the delete API endpoints does not remove the actual file.
https://github.com/nesfit/fitcrack/blob/f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/markov/markov.py#L89-L100
https://github.com/nesfit/fitcrack/blob/f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/masks/masks.py#L105-L116

Code for the delete endpoints that do not exhibit this problem does perform a file-deletion operation. Like here in the `charset` endpoint.

https://github.com/nesfit/fitcrack/blob/f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057/webadmin/fitcrackAPI/src/src/api/fitcrack/endpoints/charset/charset.py#L99-L113

If there is no reason for keeping the resource files after deleting them, I expect to be able to reuse filenames without issue. If there is a reason for this behaviour, I expect this to be documented and a more graceful error message to appear.

Given the former is probably the case and that the issue is probably caused by forgetting to add the file-deletion code, I also opened a pull request (#69) that should fix this issue if it really is that simple.

### System details
Fitcrack dev build (f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057) on Ubuntu 22.04.2

### How to reproduce
1. In Webadmin, go to Library -> Masks or go to Library -> Markov Chains
2. Upload a mask or Markov-chain file
3. Delete it
4. Try to reupload the same file
5. Get a "File with name test_add.hcmask already exists. Path: /usr/share/collections/masks/test_add.hcmask" or similar error.

[^1]: Deleted using the delete button in Webadmin.

**Comment by ihranicky** [comment]
As @davidbolvansky mentioned, we cannot just delete or edit files, as they can be dependencies of existing jobs. Possible solutions are:
a) Check if the file is not mapped to a job or
b) Generate unique filenames for each added library element (e.g. using uuid libary as @alpatron suggests).
I would go with b), but this requires of all library endpoints and editing of default DB content and default example library collection.

For the sake of the release 2.4.0, @OviOvocny will just add change the error message to a better explanation. 

@alpatron if you want, you, you can implement b). We can include this in a future release.
