### ISSUE TITLE
Generating PCFGs or Markov files from dictionaries performs no duplicate-name checks, causing issues

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#76]
Hi,

In Fitcrack Webadmin, it's impossible to upload a resource file with the same name as one that already exists. But I found out that creating Markov files or PCFGs from dictionaries performs no such duplicate-name checks. What's more, these duplicate PCFGs or Markov files are not created correctly: Creating such a duplicate Markov file causes the first one to be overwritten. And creating such a duplicate PCFG does not actually create anything—the new duplicate PCFG always has the same content as the previous PCFG.

### System details

Fitcrack dev build (f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057) on Ubuntu 22.04.2

### How to reproduce and see only the lack of duplicate checks

1. In Webadmin, go to Library -> PCFG or Markov Chains
2. Create a PCFG/Markov file from a dictionary
3. PCFG/Markov file will be created
4. Create a PCFG/Markov file from the same dictionary again
5. PCFG/Markov file will be created; there are now two PCFGs/Markov files with the same name

### How to reproduce and see that the original Markov file is overwritten

1. In Webadmin, go to Library -> Markov Chains
2. Create a Markov file from a dictionary
3. Markov file will be created
4. Download the created file back 
5. Go to Library -> Dictionary
6. Remove the dictionary used to create the Markov file
7. Add a dictionary with the same name as the deleted one, but with different content
8. Go back to Library -> Markov Chains
9. Create a Markov file from the new dictionary with the same name
10. Markov file will be created; there are now two Markov files with the same name
11. Download the Markov file again from the first entry (step 2); compare it with the previously downloaded file to see that it was overwritten 

### How to reproduce and see that no new PCFG is created

1. In Webadmin, go to Library -> PCFG
2. Create a PCFG from a dictionary
3. PCFG will be created
4. Go to Library -> Dictionary
5. Remove the dictionary used to create the Markov file
6. Add a dictionary with the same name as the deleted one, but with different content
7. Go back to Library -> PCFG
8. Create a PCFG from the new dictionary with the same name
9. PCFG will be created; there are now two PCFGs with the same name
10. Compare the two PCFGs and see that they are identical, despite the fact that they were both created from two different dictionaries

**Comment by ihranicky** [comment]
Fixed, duplicated are now checked for both Markov and PCFG. Thx for reporting.
