### ISSUE TITLE
Cannot create brute-force job with custom charsets; cannot use question-mark escape sequence in masks

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#80]
Hi,

Trying to create a job with a mask that contains a custom-charset variable ends with a "Wrong mask" error, and the mask input field on the Add Job page also shows that the mask is supposedly incorrect.

![obrazek](https://user-images.githubusercontent.com/1508117/232616414-b354bd0f-0a33-48c8-b62a-5e3b9c93c47f.png)

Moreover, masks that contain the escape sequence for the question-mark sequence (`??`) are also rejected.

![obrazek](https://user-images.githubusercontent.com/1508117/232616989-8063b2af-ee1d-4232-91e0-c4e202e0e55d.png)

It seems that the new regex introduced in the process of fixing issue #74 (3ef5abd9dea11392a16e5f35f38cc294c8d38476) is causing the issues; it now rejects too much.

It should be noted, that my proposed regex (PR #75), which was not accepted as the fix for issue #74, would not have these problems.

### How to reproduce

1. Go to Add Job and select the Brute-Force Mode
2. Select a custom charset
3. Try inputting the mask `?1` (or `??` to see the other bug described).
4. The mask input field will show that the mask is invalid
5. Try to create the job
6. Job will not be created and a "Wrong mask" error will be shown

**Comment by davidbolvansky** [comment]
Please create a new pull request with fix.

**Comment by OviOvocny** [comment]
We fixed it (hopefully) in master right now. Try it out.

**Comment by alpatron** [comment]
@OviOvocny
I can now create jobs with all the masks that were giving issues. All seems fixed. 👍
