### ISSUE TITLE
Cannot extract hashes from modern MS Office files

### ISSUE THREAD

**Issue by alpatron** [nesfit/fitcrack#81]
Hi,

I tried extracting the hash from an encrypted file generated by the latest version of Microsoft Office, and Fitcrack could not extract it.

You can try with the file here (the password is "password").
[fc_auto_test_encrypted_file.pptx](https://github.com/nesfit/fitcrack/files/11256229/fc_auto_test_encrypted_file.pptx)

It seems that updating the `office2hashcat.py` to the latest version at (<https://github.com/openwall/john/blob/bleeding-jumbo/run/office2john.py>) should fix the problem—I tried it and it succeeded.

But the newer version of the script is not a drop-in replacement because the output format of the script changed:

The older script, which is currently being used, outputs just the hash.

```
(env) C:\Users\Vikto\Desktop\seltest>python office2hashcat.py .\test\add_job_page\fc_auto_test_encrypted_file.ppt  
$oldoffice$4*f1b3dfa9af28a14897ed4d6fc251b165*fc7bb3b48a9189e681d75144fbfba0e7*8a80d439bcfc40a2d86649abcbbbbab493bbbd18
```

Whereas the latest version prepends the file name.

```
(env) C:\Users\Vikto\Desktop\seltest>python office2john.py .\test\add_job_page\fc_auto_test_encrypted_file.ppt 
fc_auto_test_encrypted_file.ppt:$oldoffice$4*f1b3dfa9af28a14897ed4d6fc251b165*fc7bb3b48a9189e681d75144fbfba0e7*8a80d439bcfc40a2d86649abcbbbbab493bbbd18
```

So I suppose `XtoHashcat.py` would need to be updated to split the output and process only the hash.

**Comment by davidbolvansky** [comment]
Just patch (drop filename from output) this new office2john.py and name it office2hashcat.py

**Comment by ihranicky** [comment]
> Just patch (drop filename from output) this new office2john.py and name it office2hashcat.py

Wont be that easy. New officec2john has a slightly different behavior, so some changes will be needed. But we can do it :)

**Comment by ihranicky** [comment]
> Different behaviour - What exactly?

office2john has a different output format than office2hashcat used in xtohashcat and thus it is not a drop-in replacement.

**Comment by ihranicky** [comment]
Fixed
