### ISSUE TITLE
Bug in MaskAttack: Weird logic for splitting keyspace

### ISSUE THREAD

**Issue by ermolushka** [nesfit/fitcrack#82]
Hi. I setup a mask attack using 3 hosts. Two of them have 7 GPUs, while the one has 3 GPU. What I observe is that the less powerful host are being assigned more and bigger chunks rather than more powerful. Also, performance of less powerful host varies a lot: it can process 209,771,829,658 keys in 1 minute and then 191,417,409,943 keys in 7.5 hours. How is that possible?

![Screenshot from 2023-04-18 19-05-32](https://user-images.githubusercontent.com/2204660/232836946-c1be6c5f-df10-4c16-aedf-34502ff345b0.png)

**Comment by ihranicky** [comment]
Hi, can you provide details about this attack and its configuration?

**Comment by davidbolvansky** [comment]
@ermolushka Can you share masks with us?

**Comment by ermolushka** [comment]
Hi. Sure:

Mask: ?u?l?l?l?l?l?l?l?d?d

Job:

Mask Attack
PDF 1.4 - 1.6 (Acrobat 5 - 8)

Markov:
[hashcat.hcstat2]

attack | attack_mode | attack_submode | distribution_mode

mask   |           3 |              2 |                 0

As far as I understood from the code: it gives bog chunks to bigger hosts and to a small one it gave smaller chunks. Then, at the end, fitcrack checked that bigger hosts are still busy and identified that the rest of keyspace can fit into a smaller host (AKA readjusting keyspace) and put it there to run for 7hours. However, would be better to check other hosts in terms of time remaining and based on this logic decide - maybe it’s better to wait for the for 5 more minutes and give them big chunks.

also, from the screenshot, not quite sure why this small host processed a big keyspace in 1 min and then 7hours (or it was not processing it?)

**Comment by davidbolvansky** [comment]
I reproduced it.

![image](https://user-images.githubusercontent.com/22410393/235937820-00274246-59be-4d0c-abd2-a59fa1d583ff.png)

First workunit after benchmark runs for one hour, others for one minute.

https://live.fitcrack.cz/jobs/8

Kinda nasty bug :/

@ihranicky

**Comment by davidbolvansky** [comment]
Spent some time on this one, it is really annoying. I dont know yet what causes this behaviour...

**Comment by davidbolvansky** [comment]
@ermolushka found the root problem, pushed fixes to dev branch. 

![image](https://github.com/nesfit/fitcrack/assets/22410393/04ed4568-3847-4e71-a3e8-69f60d523a22)
